# Generated by Django 4.2.1 on 2023-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0002_accountcredential_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcredential',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountcredential',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountcredential',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountcredential',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountcredential',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
