# Generated by Django 4.2.1 on 2023-05-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0004_accountcredential_encrypted_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcredential',
            name='password_salt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
