# Generated by Django 4.2.1 on 2023-05-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0005_accountcredential_password_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AccountCredentials.accountcredential')),
            ],
        ),
    ]
