# Generated by Django 4.2.1 on 2023-05-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0006_encryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcredential',
            name='encrypted_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
