# Generated by Django 4.2.1 on 2023-05-27 08:54

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0008_alter_accountcredential_encrypted_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcredential',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
    ]
