# Generated by Django 4.2.1 on 2023-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0009_alter_accountcredential_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcredential',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
