# Generated by Django 4.2.1 on 2023-05-28 01:20

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCredentials', '0010_accountcredential_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='key',
            field=django_cryptography.fields.encrypt(models.BinaryField()),
        ),
    ]
